import React, { useEffect, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import axios from 'axios'
import { toast } from 'react-toastify'
import
{
    Chart as ChartJS,
    CategoryScale,
    LinearScale,
    BarElement,
    Title,
    Tooltip,
    Legend,
} from 'chart.js';
import FeedbackGraph from './FeedbackGraph'
import Adminpanel from './admin/Adminpanel';

ChartJS.register(CategoryScale, LinearScale, BarElement, Title, Tooltip, Legend);

interface Feed
{
    rate1: number;
    rate2: number;
    rate3: number;
    rate4: number;
    rate5: number;
    rate6: number;
    rate7: number;
    rate8: number;
    rate9: number;
    rate10: number;
    name: string
    thoughts: string
}

interface Detail
{
    name: string
    department: string
    subject: string
    subjectcode: string
    _id: string;
}

function UniqueFeedback()
{

    const [params] = useSearchParams()
    const name = params.get("name")

    const [uniquefeed, setuniquefeed] = useState<Feed[]>([])
    const [sub_subcode, setsub_subcode] = useState<Detail | null>(null)

    const [selectedTeacher, setSelectedTeacher] = useState<Feed | null>(null)


    const [showGraph, setShowGraph] = useState<boolean>(false);
    const [analyzeTeacher, setAnalyzeTeacher] = useState<Feed | null>(null);


    useEffect(() =>
    {
        if (name)
        {
            fetchoneteacher()
        }
    }, [name])

    useEffect(() =>
    {
        document.title = "Unique Feedback";
    }, []);

    async function fetchoneteacher() 
    {
        try 
        {
            const resp = await axios.get<{ statuscode: number; uniquefeedback?: Feed[] }>(`${process.env.REACT_APP_APIURL}/api/uniquefeed/${name}`)

            if (resp.data.statuscode === 1 && resp.data.uniquefeedback) 
            {
                setuniquefeed(resp.data.uniquefeedback);
            }
            else if (resp.data.statuscode === 0) 
            {
                setuniquefeed([]);
            }
            else 
            {
                toast.error("Some Problem Occured")
            }
        }
        catch (e: any) 
        {
            toast.error("Error Occured " + e.message)
        }
    }

    useEffect(() =>
    {
        if (name)
        {
            fetchoneteacher_sub_code()
        }
    }, [name])

    async function fetchoneteacher_sub_code() 
    {
        try 
        {
            const resp = await axios.get<{ statuscode: number; sub_subcode?: Detail }>(`${process.env.REACT_APP_APIURL}/api/fetchoneteacher_sub_code/${name}`)

            if (resp.data.statuscode === 1 && resp.data.sub_subcode) 
            {
                setsub_subcode(resp.data.sub_subcode);
            }
            else if (resp.data.statuscode === 0) 
            {
                setsub_subcode(null);
            }
            else 
            {
                toast.error("Some Problem Occured")
            }
        }
        catch (e: any) 
        {
            toast.error("Error Occured " + e.message)
        }
    }

    const ratingQuestions = [
        "Knowledge base of the teacher (as perceived by you)",
        "Communication skills (in terms of articulation and comprehensibility)",
        "Sincerity / Commitment of the teacher (in terms of preparedness and interest in taking classes)",
        "Interest generated by the teacher in the class",
        "Ability to integrate course material with environment / other issues, to provide a broader perspective",
        "Accessibility and availability of the teacher in the department for academic consultations",
        "Initiative taken in formulating topics/ tests/assignments/examinations / seminars and projects",
        "Regularity in taking classes",
        "Completion of the course in a thorough and satisfactory manner",
        "Fairness in evaluating student performance and awarding grades."
    ]


    return (
        <div>
            <Adminpanel />
            <div className='content1 pad'>
                <div className='backcolor btm'>

                    {
                        uniquefeed.length > 0 ?
                            <div>
                                <h1 className='mhd33 text-center pt-4'>Performance of {uniquefeed[0].name}</h1>
                                <img src="assets/images/line1.svg" alt="underline" className="feedbackline2 mb-4" />

                                <div className='row mx-3'>
                                    {
                                        uniquefeed.map((item, index) =>
                                        {
                                            const total = (item.rate1) + (item.rate2) + (item.rate3) + (item.rate4) + (item.rate5) + (item.rate6) + (item.rate7) + (item.rate8) + (item.rate9) + (item.rate10)

                                            const div = ((item.rate1) + (item.rate2) + (item.rate3) + (item.rate4) + (item.rate5) + (item.rate6) + (item.rate7) + (item.rate8) + (item.rate9) + (item.rate10)) / 10

                                            return (
                                                <div className='col-lg-4 col-md-6 col-sm-12 mb-3' key={index}>
                                                    <div className="cardss">
                                                        <h2 className="card-titless">Teacher: {item.name}</h2>
                                                        <p className="card-subtitless">Subject: {sub_subcode?.subject}</p>
                                                        <p className="card-subtitless">Subject Code: {sub_subcode?.subjectcode}</p>
                                                        <div className="card-statsss">
                                                            <div className="ratingss">
                                                                Average Rating: <span className="rating-valuess">{div}/5</span>
                                                            </div>
                                                            <div className="total-ratingsss">
                                                                {/* Total Ratings: <span className="rating-box">{totalrating}</span> */}
                                                                Total Ratings: <span className="rating-box">{total}</span>
                                                            </div>
                                                        </div>
                                                        <div className="card-actionsss">
                                                            <button className="buttonss details-buttonss" onClick={() => setSelectedTeacher(item)}>View Details</button>
                                                            <button className="buttonss analyze-buttonss" onClick={() => { setAnalyzeTeacher(item); setShowGraph(true) }}>Analyze</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            );
                                        })
                                    }
                                </div>
                            </div> : <div className="no-user-messageee mt-5">No Feedback Found</div>
                    }

                </div>
            </div>

            {
                selectedTeacher &&
                <div className="fd-overlay">
                    <div className="fd-modal">
                        <button className="fd-close-btn" onClick={() => setSelectedTeacher(null)}>
                            <svg xmlns="http://www.w3.org/2000/svg" className="fd-close-icon" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
                            </svg>
                        </button>
                        <h3 className="fd-heading">Feedback Details</h3>
                        <div className="fd-grid">
                            {
                                ratingQuestions.map((item, index) =>
                                    <div className="fd-rating-card" key={index}>
                                        <p className="fd-question">{item}</p>
                                        <p className="fd-rating">Rating: {selectedTeacher[`rate${index + 1}` as keyof Feed]}/5</p>
                                    </div>
                                )
                            }
                        </div>
                        <div className="fd-comment">
                            <h4 className="fd-comment-heading">Comment:</h4>
                            <p className="fd-comment-text">{selectedTeacher.thoughts}</p>
                        </div>
                    </div>
                </div>
            }
            {
                showGraph && analyzeTeacher && (
                    <FeedbackGraph
                        onClose={() => setShowGraph(false)}
                        teacher={analyzeTeacher}
                        questions={ratingQuestions}
                    />
                )}

        </div>
    )
}

export default UniqueFeedback